[MeasureAudioSmoothed0]
Measure=Calc
Formula=(MeasureAudioRaw0+MeasureAudioRaw0+MeasureAudioRaw1)/12
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed1]
Measure=Calc
Formula=(MeasureAudioRaw0+MeasureAudioRaw1+MeasureAudioRaw2)/12
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed2]
Measure=Calc
Formula=(MeasureAudioRaw1+MeasureAudioRaw2+MeasureAudioRaw3)/10
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed3]
Measure=Calc
Formula=(MeasureAudioRaw2+MeasureAudioRaw3+MeasureAudioRaw4)/8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed4]
Measure=Calc
Formula=(MeasureAudioRaw3+MeasureAudioRaw4+MeasureAudioRaw5)/7
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed5]
Measure=Calc
Formula=(MeasureAudioRaw4+MeasureAudioRaw5+MeasureAudioRaw6)/6
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed6]
Measure=Calc
Formula=(MeasureAudioRaw5+MeasureAudioRaw6+MeasureAudioRaw7)/5
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed7]
Measure=Calc
Formula=(MeasureAudioRaw6+MeasureAudioRaw7+MeasureAudioRaw8)/4
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed8]
Measure=Calc
Formula=(MeasureAudioRaw7+MeasureAudioRaw8+MeasureAudioRaw9)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed9]
Measure=Calc
Formula=(MeasureAudioRaw8+MeasureAudioRaw9+MeasureAudioRaw10)/2
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed10]
Measure=Calc
Formula=(MeasureAudioRaw9+MeasureAudioRaw10+MeasureAudioRaw11)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed11]
Measure=Calc
Formula=(MeasureAudioRaw10+MeasureAudioRaw11+MeasureAudioRaw12)/2
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed12]
Measure=Calc
Formula=(MeasureAudioRaw11+MeasureAudioRaw12+MeasureAudioRaw13)/2.5
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed13]
Measure=Calc
Formula=(MeasureAudioRaw12+MeasureAudioRaw13+MeasureAudioRaw14)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed14]
Measure=Calc
Formula=(MeasureAudioRaw13+MeasureAudioRaw14+MeasureAudioRaw15)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed15]
Measure=Calc
Formula=(MeasureAudioRaw14+MeasureAudioRaw15+MeasureAudioRaw16)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed16]
Measure=Calc
Formula=(MeasureAudioRaw15+MeasureAudioRaw16+MeasureAudioRaw17)/3.25
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed17]
Measure=Calc
Formula=(MeasureAudioRaw16+MeasureAudioRaw17+MeasureAudioRaw18)/3.25
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed18]
Measure=Calc
Formula=(MeasureAudioRaw17+MeasureAudioRaw18+MeasureAudioRaw19)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed19]
Measure=Calc
Formula=(MeasureAudioRaw18+MeasureAudioRaw19+MeasureAudioRaw20)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed20]
Measure=Calc
Formula=(MeasureAudioRaw19+MeasureAudioRaw20+MeasureAudioRaw21)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed21]
Measure=Calc
Formula=(MeasureAudioRaw20+MeasureAudioRaw21+MeasureAudioRaw22)/2.5
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed22]
Measure=Calc
Formula=(MeasureAudioRaw21+MeasureAudioRaw22+MeasureAudioRaw23)/2
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed23]
Measure=Calc
Formula=(MeasureAudioRaw22+MeasureAudioRaw23+MeasureAudioRaw24)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed24]
Measure=Calc
Formula=(MeasureAudioRaw23+MeasureAudioRaw24+MeasureAudioRaw25)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed25]
Measure=Calc
Formula=(MeasureAudioRaw24+MeasureAudioRaw25+MeasureAudioRaw26)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed26]
Measure=Calc
Formula=(MeasureAudioRaw25+MeasureAudioRaw26+MeasureAudioRaw27)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed27]
Measure=Calc
Formula=(MeasureAudioRaw26+MeasureAudioRaw27+MeasureAudioRaw28)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed28]
Measure=Calc
Formula=(MeasureAudioRaw27+MeasureAudioRaw28+MeasureAudioRaw29)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed29]
Measure=Calc
Formula=(MeasureAudioRaw28+MeasureAudioRaw29+MeasureAudioRaw30)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed30]
Measure=Calc
Formula=(MeasureAudioRaw29+MeasureAudioRaw30+MeasureAudioRaw31)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed31]
Measure=Calc
Formula=(MeasureAudioRaw30+MeasureAudioRaw31+MeasureAudioRaw32)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed32]
Measure=Calc
Formula=(MeasureAudioRaw31+MeasureAudioRaw32+MeasureAudioRaw33)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed33]
Measure=Calc
Formula=(MeasureAudioRaw32+MeasureAudioRaw33+MeasureAudioRaw34)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed34]
Measure=Calc
Formula=(MeasureAudioRaw33+MeasureAudioRaw34+MeasureAudioRaw35)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed35]
Measure=Calc
Formula=(MeasureAudioRaw34+MeasureAudioRaw35+MeasureAudioRaw36)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed36]
Measure=Calc
Formula=(MeasureAudioRaw35+MeasureAudioRaw36+MeasureAudioRaw37)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed37]
Measure=Calc
Formula=(MeasureAudioRaw36+MeasureAudioRaw37+MeasureAudioRaw38)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed38]
Measure=Calc
Formula=(MeasureAudioRaw37+MeasureAudioRaw38+MeasureAudioRaw39)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed39]
Measure=Calc
Formula=(MeasureAudioRaw38+MeasureAudioRaw39+MeasureAudioRaw40)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed40]
Measure=Calc
Formula=(MeasureAudioRaw39+MeasureAudioRaw40+MeasureAudioRaw41)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed41]
Measure=Calc
Formula=(MeasureAudioRaw40+MeasureAudioRaw41+MeasureAudioRaw42)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed42]
Measure=Calc
Formula=(MeasureAudioRaw41+MeasureAudioRaw42+MeasureAudioRaw43)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed43]
Measure=Calc
Formula=(MeasureAudioRaw42+MeasureAudioRaw43+MeasureAudioRaw44)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed44]
Measure=Calc
Formula=(MeasureAudioRaw43+MeasureAudioRaw44+MeasureAudioRaw45)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed45]
Measure=Calc
Formula=(MeasureAudioRaw44+MeasureAudioRaw45+MeasureAudioRaw46)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed46]
Measure=Calc
Formula=(MeasureAudioRaw45+MeasureAudioRaw46+MeasureAudioRaw47)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed47]
Measure=Calc
Formula=(MeasureAudioRaw46+MeasureAudioRaw47+MeasureAudioRaw48)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed48]
Measure=Calc
Formula=(MeasureAudioRaw47+MeasureAudioRaw48+MeasureAudioRaw49)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed49]
Measure=Calc
Formula=(MeasureAudioRaw48+MeasureAudioRaw49+MeasureAudioRaw50)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed50]
Measure=Calc
Formula=(MeasureAudioRaw49+MeasureAudioRaw50+MeasureAudioRaw51)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed51]
Measure=Calc
Formula=(MeasureAudioRaw50+MeasureAudioRaw51+MeasureAudioRaw52)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed52]
Measure=Calc
Formula=(MeasureAudioRaw51+MeasureAudioRaw52+MeasureAudioRaw53)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed53]
Measure=Calc
Formula=(MeasureAudioRaw52+MeasureAudioRaw53+MeasureAudioRaw54)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed54]
Measure=Calc
Formula=(MeasureAudioRaw53+MeasureAudioRaw54+MeasureAudioRaw55)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed55]
Measure=Calc
Formula=(MeasureAudioRaw54+MeasureAudioRaw55+MeasureAudioRaw56)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed56]
Measure=Calc
Formula=(MeasureAudioRaw55+MeasureAudioRaw56+MeasureAudioRaw57)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed57]
Measure=Calc
Formula=(MeasureAudioRaw56+MeasureAudioRaw57+MeasureAudioRaw58)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed58]
Measure=Calc
Formula=(MeasureAudioRaw57+MeasureAudioRaw58+MeasureAudioRaw59)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed59]
Measure=Calc
Formula=(MeasureAudioRaw58+MeasureAudioRaw59+MeasureAudioRaw60)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed60]
Measure=Calc
Formula=(MeasureAudioRaw59+MeasureAudioRaw60+MeasureAudioRaw61)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed61]
Measure=Calc
Formula=(MeasureAudioRaw60+MeasureAudioRaw61+MeasureAudioRaw62)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed62]
Measure=Calc
Formula=(MeasureAudioRaw61+MeasureAudioRaw62+MeasureAudioRaw63)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed63]
Measure=Calc
Formula=(MeasureAudioRaw62+MeasureAudioRaw63+MeasureAudioRaw64)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed64]
Measure=Calc
Formula=(MeasureAudioRaw63+MeasureAudioRaw64+MeasureAudioRaw65)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed65]
Measure=Calc
Formula=(MeasureAudioRaw64+MeasureAudioRaw65+MeasureAudioRaw66)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed66]
Measure=Calc
Formula=(MeasureAudioRaw65+MeasureAudioRaw66+MeasureAudioRaw67)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed67]
Measure=Calc
Formula=(MeasureAudioRaw66+MeasureAudioRaw67+MeasureAudioRaw68)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed68]
Measure=Calc
Formula=(MeasureAudioRaw67+MeasureAudioRaw68+MeasureAudioRaw69)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed69]
Measure=Calc
Formula=(MeasureAudioRaw68+MeasureAudioRaw69+MeasureAudioRaw70)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed70]
Measure=Calc
Formula=(MeasureAudioRaw69+MeasureAudioRaw70+MeasureAudioRaw71)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed71]
Measure=Calc
Formula=(MeasureAudioRaw70+MeasureAudioRaw71+MeasureAudioRaw72)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed72]
Measure=Calc
Formula=(MeasureAudioRaw71+MeasureAudioRaw72+MeasureAudioRaw73)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed73]
Measure=Calc
Formula=(MeasureAudioRaw72+MeasureAudioRaw73+MeasureAudioRaw74)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed74]
Measure=Calc
Formula=(MeasureAudioRaw73+MeasureAudioRaw74+MeasureAudioRaw75)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed75]
Measure=Calc
Formula=(MeasureAudioRaw74+MeasureAudioRaw75+MeasureAudioRaw76)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed76]
Measure=Calc
Formula=(MeasureAudioRaw75+MeasureAudioRaw76+MeasureAudioRaw77)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed77]
Measure=Calc
Formula=(MeasureAudioRaw76+MeasureAudioRaw77+MeasureAudioRaw78)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed78]
Measure=Calc
Formula=(MeasureAudioRaw77+MeasureAudioRaw78+MeasureAudioRaw79)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed79]
Measure=Calc
Formula=(MeasureAudioRaw78+MeasureAudioRaw79+MeasureAudioRaw80)/1.8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed80]
Measure=Calc
Formula=(MeasureAudioRaw79+MeasureAudioRaw80+MeasureAudioRaw81)/2
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed81]
Measure=Calc
Formula=(MeasureAudioRaw80+MeasureAudioRaw81+MeasureAudioRaw82)/2.5
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed82]
Measure=Calc
Formula=(MeasureAudioRaw81+MeasureAudioRaw82+MeasureAudioRaw83)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed83]
Measure=Calc
Formula=(MeasureAudioRaw82+MeasureAudioRaw83+MeasureAudioRaw84)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed84]
Measure=Calc
Formula=(MeasureAudioRaw83+MeasureAudioRaw84+MeasureAudioRaw85)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed85]
Measure=Calc
Formula=(MeasureAudioRaw84+MeasureAudioRaw85+MeasureAudioRaw86)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed86]
Measure=Calc
Formula=(MeasureAudioRaw85+MeasureAudioRaw86+MeasureAudioRaw87)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed87]
Measure=Calc
Formula=(MeasureAudioRaw86+MeasureAudioRaw87+MeasureAudioRaw88)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed88]
Measure=Calc
Formula=(MeasureAudioRaw87+MeasureAudioRaw88+MeasureAudioRaw89)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed89]
Measure=Calc
Formula=(MeasureAudioRaw88+MeasureAudioRaw89+MeasureAudioRaw90)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed90]
Measure=Calc
Formula=(MeasureAudioRaw89+MeasureAudioRaw90+MeasureAudioRaw91)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed91]
Measure=Calc
Formula=(MeasureAudioRaw90+MeasureAudioRaw91+MeasureAudioRaw92)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed92]
Measure=Calc
Formula=(MeasureAudioRaw91+MeasureAudioRaw92+MeasureAudioRaw93)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed93]
Measure=Calc
Formula=(MeasureAudioRaw92+MeasureAudioRaw93+MeasureAudioRaw94)/3
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed94]
Measure=Calc
Formula=(MeasureAudioRaw93+MeasureAudioRaw94+MeasureAudioRaw95)/4
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed95]
Measure=Calc
Formula=(MeasureAudioRaw94+MeasureAudioRaw95+MeasureAudioRaw96)/5
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed96]
Measure=Calc
Formula=(MeasureAudioRaw95+MeasureAudioRaw96+MeasureAudioRaw97)/6
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed97]
Measure=Calc
Formula=(MeasureAudioRaw96+MeasureAudioRaw97+MeasureAudioRaw98)/7
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed98]
Measure=Calc
Formula=(MeasureAudioRaw97+MeasureAudioRaw98+MeasureAudioRaw99)/8
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed99]
Measure=Calc
Formula=(MeasureAudioRaw98+MeasureAudioRaw99+MeasureAudioRaw100)/9
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

[MeasureAudioSmoothed100]
Measure=Calc
Formula=(MeasureAudioRaw99+MeasureAudioRaw100+MeasureAudioRaw100)/10
AverageSize=#AverageSize#
MinValue=0
MaxValue=1

