[MeterBar0]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed0]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar1]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed1]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar2]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed2]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar3]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed3]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar4]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed4]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar5]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed5]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar6]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed6]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar7]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed7]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar8]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed8]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar9]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed9]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar10]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed10]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar11]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed11]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar12]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed12]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar13]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed13]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar14]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed14]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar15]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed15]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar16]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed16]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar17]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed17]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar18]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed18]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar19]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed19]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar20]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed20]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar21]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed21]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar22]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed22]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar23]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed23]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar24]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed24]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar25]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed25]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar26]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed26]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar27]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed27]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar28]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed28]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar29]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed29]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar30]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed30]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar31]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed31]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar32]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed32]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar33]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed33]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar34]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed34]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar35]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed35]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar36]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed36]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar37]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed37]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar38]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed38]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar39]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed39]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar40]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed40]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar41]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed41]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar42]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed42]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar43]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed43]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar44]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed44]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar45]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed45]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar46]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed46]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar47]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed47]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar48]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed48]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar49]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed49]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar50]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed50]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar51]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed51]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar52]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed52]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar53]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed53]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar54]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed54]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar55]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed55]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar56]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed56]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar57]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed57]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar58]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed58]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar59]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=7R
Y=350
Shape=Rectangle 0,0,(18*0.8),(-(350-(18*0.8))*[MeasureAudioSmoothed59]-(18*0.8)),((18*0.8)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1